
// RICE NAVI v26 full route diagnostic package

let DATA=null;
window.RICE_NAVI_APP_STARTED = false;
const app=document.getElementById('app');
const state={screen:'home', tab:'summary', q:'', route:[]};
let RANKINGS=null;
let JP_READING=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const todayIndex=len=>{const d=new Date();return Math.abs(Math.floor((d-new Date(d.getFullYear(),0,0))/86400000))%Math.max(len,1)};
function go(s){state.route.push(state.screen);state.screen=s;state.tab='summary';state.q='';render();setTimeout(()=>scrollTo(0,0),0)}
function back(){state.screen=state.route.pop()||'home';render();setTimeout(()=>scrollTo(0,0),0)}
function top(title){return `<div class="topbar"><button class="back" onclick="back()">← 戻る</button><h1>${esc(title)}</h1></div>`}
function nav(){const items=[['home','🏠','ホーム'],['learn','🌾','学ぶ'],['library','📚','文献'],['checks','✅','チェック']];return `<div class="bottom">${items.map(x=>`<button class="${state.screen===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}<br>${x[2]}</button>`).join('')}</div>`}
function cardNav(icon,title,sub,screen){return `<div class="card navcard" onclick="go('${screen}')" role="button" tabindex="0"><div class="icon">${icon}</div><div><b>${esc(title)}</b><div class="sub">${esc(sub)}</div></div><div class="chev">›</div></div>`}
function detailsCard(title, sub, body, extra=''){return `<details class="card"><summary>${esc(title)}${sub?`<div class="sub">${esc(sub)}</div>`:''}</summary>${body}${extra}</details>`}
function miniCount(label, val){return `<span class="pill"><span class="count">${esc(val)}</span> ${esc(label)}</span>`}
function home(){const f=DATA.fortunes[todayIndex(DATA.fortunes.length)], t=DATA.terms[todayIndex(DATA.terms.length)], h=DATA.histories[0], st=DATA.stories[todayIndex(DATA.stories.length)];return `<div class="content"><div class="card hero"><h2>🌾 今日の米占い</h2><h3>${esc(f.title)}</h3><p>${esc(f.message)}</p><div class="meta"><span class="pill">ラッキー米：${esc(f.rice)}</span><span class="pill">工程：${esc(f.process)}</span></div><p><b>${esc(f.word)}</b></p></div><div class="card hero"><h2>☁️ 今日の米天気</h2><div id="weatherHome"><p>現在地の天気を取得して、米の保管・吸水・結露注意に変換します。</p><button onclick="fetchWeather(true)">現在地で確認</button></div><button class="ghost" onclick="go('weather')">詳しく見る</button></div><div class="card"><h2>📝 今米言葉</h2><h3>${esc(t.term_ja)}</h3><p>${esc(t.app_note_ja||t.note_ja)}</p><div class="meta"><span class="pill">EN: ${esc(t.term_en)}</span><span class="pill">繁: ${esc(t.term_zh_tw)}</span><span class="pill">簡: ${esc(t.term_zh_cn)}</span></div><button class="secondary" onclick="go('dictionary')">米辞典で見る</button></div><div class="card"><h2>📍 現在地のお米ヒストリー</h2><h3>${esc(h.region)}</h3><p>${esc(h.body)}</p><p class="small">${esc(h.note)}</p></div><div class="card"><h2>🌏 今週のライス物語</h2><h3>${esc(st.title)}</h3><p>${esc(st.summary)}</p><button class="secondary" onclick="go('stories')">過去1か月分を見る</button></div>${cardNav('🚀','お米の未来50','50テーマをタイトル一覧から読む','future')}${cardNav('📊','世界の米ランキング','4ヶ国語対応。世界の米データを見る','rankings')}${cardNav('🍙','日本語限定読み物','米笑点・米の小噺・読み物コーナー','jp_reading')}${cardNav('📚','炊飯文献ライブラリ','カード・claim・出典を詳しく見る','library')}${cardNav('🎓','お米マイスター100','初級30・中級40・上級30','meister')}${cardNav('🔎','米品種図鑑','250件マスター反映。未確認は未確認表示','varieties')}${cardNav('💧','水の相性チェック','地域参考水質・スケール注意','water')}${cardNav('🏚️','納米庫チェッカー','結露・温湿度・危険サイン','mold')}</div>`}
function stories(){const start=todayIndex(DATA.stories.length);let items=[];for(let i=0;i<5;i++)items.push(DATA.stories[(start-i+DATA.stories.length)%DATA.stories.length]);return `<div class="content">${top('世界のライス物語')}<p class="sub">今週＋先週から過去1か月分だけを表示します。全件表示はしません。</p>${items.map((x,i)=>detailsCard((i?'過去':'今週')+'：'+x.title,`第${x.week}週`, `<p>${esc(x.body)}</p>`)).join('')}<button class="secondary" onclick="alert('全件検索は別画面に分ける設計です。ホームや過去表示では全件を出しません。')">すべてのストーリーを探す</button></div>`}
function future(){return `<div class="content">${top('お米の未来')}<div class="meta">${miniCount('テーマ',DATA.future.length)}</div><input class="filter" placeholder="検索" oninput="state.q=this.value;render()" value="${esc(state.q)}">${DATA.future.filter(x=>(x.title+x.category+x.subtitle).includes(state.q)).map(x=>detailsCard(x.title,`${x.category}｜${x.subtitle}`,`<p>${esc(x.body)}</p><div class="source">${esc(x.source_type)} / ${esc(x.source_note)}<br>${esc(x.source_url)}</div>`)).join('')}</div>`}
function dictionary(){return `<div class="content">${top('米辞典')}<p class="sub">既存の米言葉データをそのまま使用しています。</p><input class="filter" placeholder="用語検索" oninput="state.q=this.value;render()" value="${esc(state.q)}">${DATA.terms.filter(t=>(t.term_ja+t.term_en+t.term_zh_tw+t.term_zh_cn).includes(state.q)).map(t=>`<div class="card"><h3>${esc(t.term_ja)}</h3><p>${esc(t.app_note_ja||t.note_ja)}</p><div class="meta"><span class="pill">EN ${esc(t.term_en)}</span><span class="pill">繁 ${esc(t.term_zh_tw)}</span><span class="pill">簡 ${esc(t.term_zh_cn)}</span></div></div>`).join('')}</div>`}
function meister(){const levels=['初級','中級','上級'];return `<div class="content">${top('お米マイスター100')}<div class="meta">${levels.map(l=>miniCount(l,DATA.meister.filter(x=>x.level===l).length)).join('')}</div>${levels.map(level=>`<div class="card"><h2>${level}</h2>${DATA.meister.filter(x=>x.level===level).map(x=>`<details class="detail"><summary>${x.no}. ${esc(x.title)}</summary><p>${esc(x.body)}</p><p><b>今日のポイント</b><br>${esc(x.point)}</p><button class="ghost" onclick="go('library')">関連する根拠を見る</button></details>`).join('')}</div>`).join('')}</div>`}
function library(){const tabs=[['summary','概要'],['cards','文献カード'],['claims','工程claim'],['waterclaim','水質claim'],['moldclaim','納米庫claim'],['temp','温度×時間']];let body='';if(state.tab==='summary')body=`<div class="card"><h2>文献ライブラリ収録状況</h2><div class="meta">${miniCount('文献カード',DATA.learning_cards.length)}${miniCount('工程claim',DATA.process_claims.length)}${miniCount('水質claim',DATA.water_claims.length)}${miniCount('納米庫claim',DATA.mold_claims.length)}</div><p>一覧は軽く、詳細リンク先に本文・条件・注意・参照IDをまとめる設計です。</p></div>`;if(state.tab==='cards')body=listCards(DATA.learning_cards,'title','short',c=>`<p>${esc(c.easy)}</p><p><b>条件・数値</b><br>${esc(c.numbers)}</p><div class="source">claim: ${esc(c.claim_ids)}<br>source: ${esc(c.source_ids)}</div>`);if(state.tab==='claims')body=listCards(DATA.process_claims,'theme','claim',c=>`<p><b>条件</b><br>${esc(c.condition)}</p><div class="source">claim_id: ${esc(c.id)} / source_id: ${esc(c.source_id)}</div>`);if(state.tab==='waterclaim')body=listCards(DATA.water_claims,'topic','claim_ja',c=>`<p>${esc(c.display_caution_ja)}</p><div class="source">${esc(c.source_id)}<br>${esc(c.source_url)}</div>`);if(state.tab==='moldclaim')body=listCards(DATA.mold_claims,'theme','claim_ja',c=>`<p><b>使い方</b><br>${esc(c.use_in_rule)}</p><p class="small">${esc(c.limitations)}</p>`);if(state.tab==='temp')body=DATA.temp_map.map(t=>`<div class="card"><h3>${esc(t.stage)}</h3><div class="meta"><span class="pill">${esc(t.temp)}</span><span class="pill">${esc(t.time)}</span></div><p>${esc(t.event)}</p><p><b>見るポイント</b><br>${esc(t.watch)}</p></div>`).join('');return `<div class="content">${top('炊飯文献ライブラリ')}<div class="tabs">${tabs.map(t=>`<button class="tab ${state.tab===t[0]?'active':''}" onclick="state.tab='${t[0]}';state.q='';render();scrollTo(0,0)">${t[1]}</button>`).join('')}</div>${state.tab!=='summary'?`<input class="filter" placeholder="検索" oninput="state.q=this.value;render()" value="${esc(state.q)}">`:''}${body}</div>`}
function listCards(arr,titleKey,subKey,detailFn){return arr.filter(x=>JSON.stringify(x).includes(state.q)).slice(0,300).map(x=>detailsCard(x[titleKey]||x.id,x[subKey]||'',detailFn(x))).join('')}
function varieties(){let q=state.q;let list=DATA.varieties.filter(v=>JSON.stringify(v).includes(q));const total=DATA.varieties.length;const shown=list.slice(0,250);return `<div class="content">${top('米品種図鑑')}<div class="card"><h2>250件マスター反映済み</h2><p>米品種マスターJSONから${esc(total)}件を読み込みました。検索すると対象品種だけに絞り込めます。</p><p class="small">${esc(DATA.variety_catalog_status.policy)}</p><div class="meta"><span class="pill">総件数：${esc(total)}件</span><span class="pill">アミロース情報：${esc(DATA.variety_catalog_status.amylose_available)}件</span><span class="pill">たんぱく質情報：${esc(DATA.variety_catalog_status.protein_available)}件</span></div></div><input class="filter" placeholder="品種名・国・地域・用途・食感で検索" oninput="state.q=this.value;render()" value="${esc(state.q)}"><p class="small">表示：${esc(shown.length)}件 / 該当：${esc(list.length)}件</p>${shown.map(v=>`<details class="card"><summary><b>${esc(v.display_name_ja||v.variety_name||v.id)}</b><div class="sub">${esc(v.country_ja||v.origin_country_ja||'未確認')} / ${esc(v.rice_type||'未確認')} / ${esc(v.grain_shape||'未確認')}</div></summary><div class="meta"><span class="pill">ID：${esc(v.id)}</span><span class="pill">国・地域：${esc(v.country_ja||v.origin_country_ja||'未確認')}</span><span class="pill">信頼度：${esc(v.source_confidence||'未確認')}</span></div><p><b>特徴・食感</b><br>${esc(v.texture_tags||v.app_summary_ja_v1_7||v.app_summary_ja_v1_6||'未確認')}</p><p><b>用途</b><br>${esc(v.main_uses||v.use_category_primary||'未確認')}</p><p><b>香り</b>：${esc(v.aroma||'未確認')}</p><p><b>アミロース</b>：${esc(v.amylose_range||v.amylose_value||'未確認')}<br><b>たんぱく質</b>：${esc(v.protein_range||v.protein_value||'未確認')}</p><p><b>炊飯ポイント</b><br>${esc(v.cooking_points||v.safe_app_note_ja_v1_4||'未確認')}</p><p><b>主な地域・市場</b><br>${esc(v.main_production_regions||'未確認')} / ${esc(v.main_consumption_markets||'未確認')}</p><div class="source">出典種別：${esc(v.source_type||'未確認')}<br>出典ID：${esc(v.source_ids||'未確認')}<br>${esc(v.notes||v.app_caution_ja_v1_7||'')}</div></details>`).join('')}</div>`}
function water(){return `<div class="content">${top('水の相性チェック')}<div class="card"><h2>現在地で参考表示</h2><p>GPSは地域推定だけに使います。水質を測定するものではありません。</p><button onclick="useGeoForWater()">現在地から地域を確認</button><div id="waterRegion" class="detail hidden"></div></div><div class="card"><h2>硬度・炊飯アドバイス</h2>${DATA.water_rules.filter(r=>r.parameter==='total_hardness').map(r=>detailsCard(r.class_ja,`${r.min_value}〜${r.max_value||'以上'} ${r.unit}`,`<p>${esc(r.advice_ja)}</p><p><b>注意</b><br>${esc(r.demerit_ja)}</p>`)).join('')}</div><div class="card"><h2>設備スケール注意</h2>${DATA.scale_rules.slice(0,8).map(r=>detailsCard(r.risk_ja,r.parameter,`<p>${esc(r.mechanism_ja)}</p><p>${esc(r.equipment_impact_ja)}</p><p><b>確認</b><br>${esc(r.recommended_action_ja)}</p>`)).join('')}</div></div>`}
function useGeoForWater(){const el=document.getElementById('waterRegion');el.classList.remove('hidden'); if(!navigator.geolocation){el.innerHTML='このブラウザではGPSが使えません。地域参考値は手動選択にしてください。';return} navigator.geolocation.getCurrentPosition(pos=>{el.innerHTML=`緯度 ${pos.coords.latitude.toFixed(3)} / 経度 ${pos.coords.longitude.toFixed(3)}<p>地域水質DB接続前のため、水質値は未確認です。建物配管・貯水槽・浄水器・処理水で実水質は変わります。</p>`},err=>{el.innerHTML='位置情報を取得できませんでした。地域参考値は未確認として扱います。'});}
function weather(){return `<div class="content">${top('今日の米天気')}<div class="card"><h2>現在地の天気を取得</h2><p>Open-Meteoの無料APIを使い、気温・湿度・雨を米の保管・吸水・結露注意に変換します。</p><button onclick="fetchWeather(false)">現在地で取得</button><div id="weatherDetail" class="detail"></div></div><div class="card"><h2>米への変換ルール</h2><p>湿度が高い日は、米袋・保管室・納米庫の結露、カビ臭、濡れた米粒を確認します。</p><p>低温日や冷えた米では吸水が遅くなる可能性があるため、浸漬時間・水温・洗米後重量を見ます。</p></div></div>`}
function fetchWeather(home){const target=home?document.getElementById('weatherHome'):document.getElementById('weatherDetail');target.innerHTML='取得中...';if(!navigator.geolocation){target.innerHTML='GPSが使えません。湿度70％以上、気温差が大きい日は結露に注意してください。';return}navigator.geolocation.getCurrentPosition(async pos=>{try{let lat=pos.coords.latitude, lon=pos.coords.longitude;let url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,precipitation&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=auto`;let r=await fetch(url);let j=await r.json();let c=j.current||{};let temp=c.temperature_2m, hum=c.relative_humidity_2m, rain=c.precipitation;let advice=[]; if(hum>=70)advice.push('湿度が高めです。結露・カビ臭・濡れた米粒に注意。'); if(temp>=28)advice.push('高温です。保管温度と虫・劣化リスクを確認。'); if(temp<=15)advice.push('低温です。米と水が冷えている場合、吸水が遅くなる可能性。'); if(rain>0)advice.push('雨があります。搬入時の濡れ・袋表面の水分に注意。'); if(!advice.length)advice.push('大きな注意は少なめですが、保管室の実測温湿度を優先してください。');target.innerHTML=`<h3>${temp}℃ / 湿度${hum}%</h3><p>${advice.join('<br>')}</p><button class="ghost" onclick="go('mold')">納米庫チェッカーへ</button>`}catch(e){target.innerHTML='天気API取得に失敗しました。湿度・温度は現場実測を優先してください。'}} ,err=>{target.innerHTML='位置情報を取得できませんでした。湿度・温度は現場実測を優先してください。'});}
function mold(){let rules=DATA.mold_rules||[], checks=DATA.mold_checklist||[];return `<div class="content">${top('納米庫チェッカー')}<div class="card"><h2>結露・カビの考え方</h2><p>納米庫は、温度差・湿度・残留米・清掃状態の組み合わせで見るページです。チェックだけでなく、なぜ危ないかを学びます。</p></div><div class="card warn"><h2>温湿度の目安</h2><p>相対湿度70％以上は注意域。65％前後以下を管理しやすい目安として見ますが、安全保証ではありません。</p><p>20〜30℃程度では多くのカビが増えやすい温度帯として注意します。低温でも温度差があると結露します。</p></div><div class="card danger"><h2>危険サイン</h2>${rules.filter(r=>r.rule_type==='即時停止').map(r=>`<p>・${esc(r.condition_ja)}：${esc(r.message_ja)}</p>`).join('')||'<p>目視カビ、カビ臭、濡れた残留米、不明変色、大量虫は使用前に品質確認。</p>'}</div><div class="card"><h2>見る場所</h2>${checks.map(c=>detailsCard(c.check_area,c.check_item,`<p>方法：${esc(c.method)}</p><p>NG時：${esc(c.action_if_ng)}</p>`)).join('')}</div></div>`}
function environment(){return `<div class="content">${top('気温・湿度・保管環境')}<div class="card"><h2>天気と米の状態</h2><p>高温・高湿・雨・気温差は、保管、吸水、結露、納米庫の確認ポイントに変換して見ます。</p><button onclick="go('weather')">今日の米天気を見る</button></div><div class="card"><h2>現場で見る項目</h2><p>外気温、室温、湿度、米温、袋表面の水分、床・壁の結露、におい、虫、残留米。</p></div></div>`}
function checks(){return `<div class="content">${top('チェック')} ${cardNav('☁️','今日の米天気','天気を米の注意に変換','weather')}${cardNav('💧','水の相性チェック','地域水質参考・炊飯アドバイス','water')}${cardNav('🌡️','気温・湿度・保管環境','保管・吸水・カビリスク','environment')}${cardNav('🏚️','納米庫チェッカー','結露・残留米・カビ臭','mold')}</div>`}
function learn(){return `<div class="content">${top('学ぶ')} ${cardNav('📝','米辞典','既存の米言葉データ','dictionary')}${cardNav('🎓','お米マイスター100','初級・中級・上級','meister')}${cardNav('📚','炊飯文献ライブラリ','根拠とclaim','library')}${cardNav('🔎','米品種図鑑','250件の品種・特徴・用途','varieties')}${cardNav('🌏','世界のライス物語','今週と過去1か月','stories')}${cardNav('🚀','お米の未来','50テーマ','future')}${cardNav('📊','世界の米ランキング','4ヶ国語対応','rankings')}${cardNav('🍙','日本語限定読み物','米笑点・読み物コーナー','jp_reading')}</div>`}

function getJa(x){return (x&&typeof x==='object')?(x.ja||x['ja']||x.en||''):(x||'')}
function getLangText(x){
  if(!x || typeof x!=='object') return x||'';
  const lang = (document.documentElement.lang||'ja').toLowerCase();
  if(lang.includes('zh') && lang.includes('tw')) return x.zh_tw||x['zh-TW']||x.ja||x.en||'';
  if(lang.includes('zh')) return x.zh_cn||x['zh-CN']||x.ja||x.en||'';
  if(lang.includes('en')) return x.en||x.ja||'';
  return x.ja||x.en||'';
}
function ensureRankings(){if(RANKINGS){render();return} const box=document.getElementById('rankingsLoading'); if(box)box.innerHTML='読込中...'; fetch('data/world_rice_rankings/rice_navi_world_rice_rankings_master_v1_multilingual.json?v=26', {cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('rankings load failed '+r.status);return r.json()}).then(j=>{RANKINGS=j;render();setTimeout(()=>scrollTo(0,0),0)}).catch(e=>{if(box)box.innerHTML='世界の米ランキングデータを読み込めませんでした：'+esc(e.message);});}
function rankings(){if(!RANKINGS){setTimeout(ensureRankings,0);return `<div class="content">${top('世界の米ランキング')}<div class="card"><h2>世界の米ランキング</h2><p>4ヶ国語データを持つランキング機能です。初回表示時だけ別データを読み込むため、起動は重くしません。</p><div id="rankingsLoading">読込準備中...</div></div></div>`}
 const rankings=(RANKINGS.rankings||[]).filter(r=>r.status!=='inactive');
 const cats=[...new Set(rankings.map(r=>getLangText(r.category)).filter(Boolean))];
 let q=state.q;
 let list=rankings.filter(r=>(getLangText(r.ranking_name)+getLangText(r.display_title)+getLangText(r.short_desc)+getLangText(r.value)+getLangText(r.category)).includes(q));
 return `<div class="content">${top('世界の米ランキング')}<div class="card"><h2>世界の米ランキング</h2><p>米の生産・消費・輸出入・面積・単収など、世界の米データを読む機能です。日本語限定ではありません。</p><div class="meta"><span class="pill">ランキング案：${esc(rankings.length)}件</span><span class="pill">カテゴリ：${esc(cats.length)}件</span><span class="pill">4ヶ国語対応</span></div><p class="small">実順位データが未入力のランキングは、出典確認後に数値を入れる設計です。仮順位は表示しません。</p></div><input class="filter" placeholder="ランキング名・テーマで検索" oninput="state.q=this.value;render()" value="${esc(state.q)}">${list.map(r=>detailsCard(getLangText(r.display_title)||getLangText(r.ranking_name),`${getLangText(r.category)}｜${getLangText(r.value)}`,`<p>${esc(getLangText(r.short_desc))}</p><p><b>出典候補</b><br>${esc(r.source_name||'未確認')}</p><p><b>単位・計算</b><br>${esc(r.unit||'未確認')} / ${esc(r.calculation_method||'未確認')}</p><p><b>注意</b><br>${esc(getLangText(r.caution)||'実順位データは出典確認後に入力します。')}</p>${(r.items&&r.items.length)?`<ol>${r.items.map(i=>`<li>${esc(i.country_ja||i.name_ja||i.country||i.name)} ${esc(i.value||'')}</li>`).join('')}</ol>`:'<p class="small">順位表は未入力です。読み物タイトル・説明・出典候補のみ表示しています。</p>'}`)).join('')}</div>`}
function ensureJpReading(){if(JP_READING){render();return} const box=document.getElementById('jpReadingLoading'); if(box)box.innerHTML='読込中...'; fetch('data/jp_reading_corner/rice_navi_jp_reading_corner_yoneshoten.json?v=26', {cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('jp reading load failed '+r.status);return r.json()}).then(j=>{JP_READING=j;render();setTimeout(()=>scrollTo(0,0),0)}).catch(e=>{if(box)box.innerHTML='日本語限定読み物データを読み込めませんでした：'+esc(e.message);});}
function jpReading(){if(!JP_READING){setTimeout(ensureJpReading,0);return `<div class="content">${top('日本語限定読み物')}<div class="card"><h2>日本語限定読み物</h2><p>米笑点・米目線の読み物など、日本語で読む軽い読み物コーナーです。</p><div id="jpReadingLoading">読込準備中...</div></div></div>`}
 const items=(JP_READING.items||[]).filter(x=>String(x.status||'').includes('採用'));
 const series=[...new Set(items.map(x=>x.series_name).filter(Boolean))];
 let q=state.q;
 let list=items.filter(x=>JSON.stringify(x).includes(q));
 return `<div class="content">${top('日本語限定読み物')}<div class="card"><h2>日本語限定読み物</h2><p>このコーナーだけ日本語限定です。米笑点、米の本音、米目線の工程読み物などをまとめています。</p><div class="meta"><span class="pill">収録：${esc(items.length)}件</span><span class="pill">企画：${esc(series.length)}件</span><span class="pill">日本語限定</span></div><p class="small">米占いとは別管理です。おこげネタは基本使用しません。</p></div><input class="filter" placeholder="タイトル・企画名で検索" oninput="state.q=this.value;render()" value="${esc(state.q)}">${list.map(x=>detailsCard(x.title_or_question||x.title_ja||x.title||x.series_name,`${x.series_name||''}｜${x.status||''}`,`<p>${esc(x.text_ja||'')}</p><p class="small">${esc(x.note||x.source_note||'')}</p>`)).join('')}</div>`}

function render(){let main='';const s=state.screen;if(s==='home')main=home();else if(s==='stories')main=stories();else if(s==='future')main=future();else if(s==='dictionary')main=dictionary();else if(s==='meister')main=meister();else if(s==='library')main=library();else if(s==='varieties')main=varieties();else if(s==='water')main=water();else if(s==='weather')main=weather();else if(s==='mold')main=mold();else if(s==='environment')main=environment();else if(s==='rankings')main=rankings();else if(s==='jp_reading')main=jpReading();else if(s==='checks')main=checks();else if(s==='learn')main=learn();else main=home();app.innerHTML=`<div class="app"><div class="header"><img src="assets/RICE_NAVI_RN_icon.png" class="logo"><div class="brand">RICE NAVI<small>Rice learning & reference</small></div></div>${main}${nav()}</div>`}
fetch('data/rice_navi_data_v26.json?v=26', {cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('data load failed '+r.status);return r.json()}).then(j=>{DATA=j;window.RICE_NAVI_APP_STARTED=true;render()}).catch(e=>{window.RICE_NAVI_APP_STARTED=true;app.innerHTML=`<div class="app"><div class="header"><div class="brand">RICE NAVI</div></div><div class="error"><h2>データ読込エラー</h2><p>${esc(e.message)}</p><p>GitHubにアップロードするときは、index.html / app.js / styles.css / assets / data を同じ階層に置いてください。</p></div></div>`});

  