
const S={data:null,view:'home',lang:'ja',filters:{}};
const $=s=>document.querySelector(s); const el=(tag,cls,html)=>{const e=document.createElement(tag); if(cls)e.className=cls; if(html!==undefined)e.innerHTML=html; return e};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function t(obj,base='title'){ if(!obj) return ''; const L=S.lang; const keys={ja:[base,base+'_ja','ja'],en:[base+'_en','en'],zh_tw:[base+'_zh_tw',base+'_zhTW','zhTW'],zh_cn:[base+'_zh_cn',base+'_zhCN','zhCN']}; for(const k of keys[L]||keys.ja){ if(obj[k]) return obj[k]; } for(const k of keys.ja){ if(obj[k]) return obj[k]; } return ''; }
function todayIndex(n, salt=''){ if(!n)return 0; const d=new Date(); const s=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}-${salt}`; let h=0; for(let i=0;i<s.length;i++) h=(h*31+s.charCodeAt(i))>>>0; return h%n; }
function pick(arr,salt){ return arr&&arr.length?arr[todayIndex(arr.length,salt)]:null; }

const countLabels={
  literature_cards_v74:'炊飯文献カード', field_notes_v74:'現場メモ', v72_claims:'v72根拠', v72_sources:'v72出典',
  learning_cards_v82:'教材カード', glossary_terms:'米辞典', rice_varieties:'米品種', future_rice:'お米の未来',
  ranking_definitions:'ランキング定義', ranking_template_rows:'ランキング入力枠', water_rules:'水質ルール', scale_rules:'スケール判定',
  water_claims:'水質根拠', mold_claims:'保管衛生根拠', mold_rules:'納米庫ルール', mold_checklist:'納米庫点検'
};
function countLabel(k){return countLabels[k]||k;}

function switchView(v){ S.view=v; document.querySelectorAll('.view').forEach(x=>x.classList.remove('active')); $('#'+v).classList.add('active'); document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function card(title, body, extra=''){ return `<div class="card"><h2>${esc(title)}</h2>${body}${extra}</div>`; }
function chips(list){ return (list||[]).filter(Boolean).slice(0,8).map(x=>`<span class="pill">${esc(x)}</span>`).join(''); }
function showDetail(title, html){ $('#detail').innerHTML=`<div class="hero"><h1>${esc(title)}</h1><button class="btn secondary" onclick="history.back();switchView('${S.view==='detail'?'home':S.view}')">戻る</button></div><div class="card">${html}</div>`; document.querySelectorAll('.view').forEach(x=>x.classList.remove('active')); $('#detail').classList.add('active'); window.scrollTo({top:0,behavior:'smooth'}); }
async function load(){ const res=await fetch('data/rice_navi_data_v32.json?v=32'); S.data=await res.json(); document.querySelectorAll('.bottomnav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view)); $('#lang').onchange=e=>{S.lang=e.target.value; render()}; render(); }
function render(){ if(!S.data)return; renderHome(); renderLearn(); renderLiterature(); renderVarieties(); renderCheck(); renderFuture(); renderRankings(); }
function renderHome(){ const d=S.data; const v=pick(d.rice_varieties,'variety'); const lc=pick(d.learning_cards,'learn'); const term=pick(d.glossary,'term'); const fut=pick(d.future_rice,'future'); const lit=pick(d.literature.cards,'lit'); const fortuneWords=['吸水運','粒立ち運','ふっくら運','温度管理運','水加減運','蒸らし運','保管注意運']; const fortune=fortuneWords[todayIndex(fortuneWords.length,'fortune')]; $('#home').innerHTML=`<div class="hero"><h1>RICE NAVI v31</h1><p>見た目だけではなく、v74文献428件、教材82件、米品種250件、保管・水質・未来データを分けて使う版です。</p></div>
<div class="countbar">${Object.entries(d.counts).map(([k,v])=>`<div class="kpi"><b>${esc(v)}</b><span>${esc(countLabel(k))}</span></div>`).join('')}</div>
<div class="grid" style="margin-top:14px">
${card('今日の米占い',`<p><b>${fortune}</b></p><p>ラッキー米種：${esc(v?.display_name_ja||v?.name_ja||v?.variety_name_ja||v?.name||'米品種')}</p><p>ラッキー工程：${esc(lc?.title||'浸漬・吸水')}</p><p>今日の米言葉：${esc(t(term,'term')||t(term,'title')||'吸水')}</p>`)}
${card('今日のお米',`<p><b>${esc(v?.display_name_ja||v?.name_ja||v?.variety_name_ja||v?.name||'品種名未確認')}</b></p><p>${esc(v?.country_ja||v?.origin_country_ja||v?.country||'国・地域未確認')} / ${esc(v?.rice_type_ja||v?.type_ja||'種類未確認')}</p><p>${esc(v?.main_use_ja||v?.use_ja||v?.feature_ja||'用途・特徴は詳細で確認')}</p><button class="btn" onclick="switchView('varieties')">米品種図鑑へ</button>`)}
${card('今日の学習カード',`<p><b>${esc(lc?.title)}</b></p><p>${esc(lc?.short||lc?.easy||'')}</p><p>${chips([lc?.priority,lc?.evidence_level,lc?.related_terms])}</p><button class="btn" onclick="switchView('learn')">教材を見る</button>`)}
${card('今日の文献カード',`<p><b>${esc(lit?.title)}</b></p><p>${esc(lit?.category)} / ${esc(lit?.decision)}</p><p class="meta">出典ID：${esc(lit?.source_ids||'未確認')} / 根拠ID：${esc(lit?.claim_ids||'未確認')}</p><button class="btn" onclick="switchView('literature')">文献ライブラリへ</button>`)}
${card('お米の未来',`<p><b>${esc(fut?.title_ja||fut?.title)}</b></p><p>${esc(fut?.subtitle_ja||fut?.summary_ja||fut?.summary||'')}</p><button class="btn" onclick="switchView('future')">未来50を見る</button>`)}
${card('納米庫管理・水の相性',`<p>湿度・温度・結露・残米・カビ臭・水質を、チェックと根拠から確認します。</p><button class="btn" onclick="switchView('check')">チェックへ</button>`)}
</div>`; }
function renderLearn(){ const data=S.data.learning_cards||[]; const cats=[...new Set(data.map(x=>x.priority||x.module||'教材').filter(Boolean))]; const q=S.filters.learn||''; const list=data.filter(x=>!q||JSON.stringify(x).includes(q)).slice(0,200); $('#learn').innerHTML=`<div class="hero"><h1>お米マイスター / 教材</h1><p>82件の教材カード。文献ライブラリとは分け、学びやすい入口として使います。</p></div><div class="toolbar"><input placeholder="教材検索" value="${esc(q)}" oninput="S.filters.learn=this.value;renderLearn()">${chips(cats)}</div><div class="list">${list.map((x,i)=>`<div class="item"><h3>${esc(x.title)}</h3><p>${esc(x.short||x.easy||'')}</p><p>${chips([x.evidence_level,x.priority,x.related_terms])}</p><details><summary>条件・注意・出典</summary><p>${esc(x.numbers_conditions||'条件未確認')}</p><p>${esc(x.warning||'')}</p><div class="source">出典ID: ${esc(x.source_ids||'未確認')}<br>根拠ID: ${esc(x.claim_ids||'未確認')}</div></details></div>`).join('')}</div>`; }
function renderLiterature(){ const cards=S.data.literature.cards||[]; const notes=S.data.literature.field_notes||[]; const q=S.filters.litq||''; const cat=S.filters.litcat||''; const cats=[...new Set(cards.map(x=>x.category).filter(Boolean))].sort(); const filtered=cards.filter(x=>(!q||JSON.stringify(x).includes(q))&&(!cat||x.category===cat)); $('#literature').innerHTML=`<div class="hero"><h1>炊飯文献ライブラリ</h1><p>v74の428件を中心に表示します。82件教材とは分けています。現場メモ126件は正式文献カードと別枠です。</p></div>
<div class="toolbar"><input placeholder="文献カード検索" value="${esc(q)}" oninput="S.filters.litq=this.value;renderLiterature()"><select onchange="S.filters.litcat=this.value;renderLiterature()"><option value="">全カテゴリ</option>${cats.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('')}</select></div>
<div class="countbar"><div class="kpi"><b>${cards.length}</b><span>v74文献カード</span></div><div class="kpi"><b>${notes.length}</b><span>現場メモ</span></div><div class="kpi"><b>${S.data.literature.claims.length}</b><span>v72根拠</span></div><div class="kpi"><b>${S.data.literature.sources.length}</b><span>追加出典</span></div></div>
<div class="list" style="margin-top:12px">${filtered.slice(0,220).map(x=>`<div class="item"><h3>${esc(x.title)}</h3><p>${chips([x.category,x.type,x.decision,x.trace])}</p><p>${esc(x.summary||'')}</p><details><summary>根拠を見る</summary><p>${esc(x.condition||'条件・注意は未入力')}</p><div class="source">ID: ${esc(x.id)}<br>出典ID: ${esc(x.source_ids||'未確認')}<br>根拠ID: ${esc(x.claim_ids||'未確認')}<br>確認状態: ${esc(x.status||'未確認')}</div></details></div>`).join('')}</div>
<div class="section-title"><h2>現場メモ</h2><span class="meta">正式文献カードとは別枠</span></div><div class="list">${notes.slice(0,40).map(n=>`<div class="item"><h3>${esc(n.title)}</h3><p>${chips([n.category,n.decision])}</p><p>${esc(n.summary)}</p><details><summary>扱い</summary><p>${esc(n.condition)}</p><div class="source">${esc(n.source_or_policy)}</div></details></div>`).join('')}</div>`; }
function renderVarieties(){ const data=S.data.rice_varieties||[]; const q=S.filters.varq||''; const country=S.filters.country||''; const countryKeys=['country_ja','origin_country_ja','country','production_country_ja','main_country_ja']; const getCountry=x=>countryKeys.map(k=>x[k]).find(Boolean)||'国・地域未確認'; const countries=[...new Set(data.map(getCountry))].sort(); const filtered=data.filter(x=>(!q||JSON.stringify(x).includes(q))&&(!country||getCountry(x)===country)); $('#varieties').innerHTML=`<div class="hero"><h1>米品種図鑑</h1><p>250件を検索・国別一覧・今日のお米に使います。未確認項目は空欄にせず未確認として扱います。</p></div><div class="toolbar"><input placeholder="品種検索" value="${esc(q)}" oninput="S.filters.varq=this.value;renderVarieties()"><select onchange="S.filters.country=this.value;renderVarieties()"><option value="">全ての国・地域</option>${countries.map(c=>`<option ${c===country?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="list">${filtered.slice(0,250).map(x=>{let name=x.display_name_ja||x.name_ja||x.variety_name_ja||x.name||x.variety||'品種名未確認'; return `<div class="item"><h3>${esc(name)}</h3><p>${chips([getCountry(x),x.rice_type_ja||x.type_ja,x.grain_shape_ja||x.grain_shape])}</p><p>アミロース：${esc(x.amylose||x.amylose_percent||'未確認')} / たんぱく質：${esc(x.protein||x.protein_percent||'未確認')}</p><p>${esc(x.main_use_ja||x.use_ja||x.feature_ja||x.texture_ja||'特徴・用途は未確認')}</p><details><summary>詳細・出典</summary>${Object.entries(x).filter(([k,v])=>v&&String(v).trim()).slice(0,30).map(([k,v])=>`<p><b>${esc(k)}</b>: ${esc(v)}</p>`).join('')}</details></div>`}).join('')}</div>`; }
function renderCheck(){ const w=S.data.water, m=S.data.storage_mold; $('#check').innerHTML=`<div class="hero"><h1>チェック</h1><p>水の相性、納米庫管理、保管・カビ衛生を分けて表示します。GPSは水質を実測しません。</p></div><div class="grid">
${card('水の相性チェック',`<p>硬度・pH・TDS・残留塩素は、地域または手入力値から傾向を見ます。</p><p>${chips(['水質ルール '+w.quality_rules.length,'水質根拠 '+w.claims.length,'地域テンプレ '+w.regions.length])}</p><details><summary>硬度ルール</summary>${w.quality_rules.slice(0,6).map(r=>`<p><b>${esc(r.class_ja)}</b> ${esc(r.min_value)}〜${esc(r.max_value||'以上')} ${esc(r.unit)}<br>${esc(r.advice_ja)}</p>`).join('')}</details>`)}
${card('納米庫管理',`<p>温度・湿度・結露・残米・付着米・カビ臭・虫・清掃判断を確認します。</p><p>${chips(['判定ルール '+m.rules.length,'チェック項目 '+m.checklist.length,'衛生根拠 '+m.claims.length])}</p><details open><summary>点検リスト</summary>${m.checklist.slice(0,12).map(c=>`<p>・${esc(c.check_item_ja||c.item_ja||c.title_ja||JSON.stringify(c).slice(0,80))}</p>`).join('')}</details>`)}
${card('出典・根拠',`<p>水質・スケール・カビ衛生の根拠を分けて表示します。</p><details><summary>水質出典</summary>${w.sources.slice(0,8).map(s=>`<div class="source"><b>${esc(s.source_id)}</b> ${esc(s.source_title_ja)}<br>${esc(s.source_url)}</div>`).join('')}</details><details><summary>カビ衛生出典</summary>${m.sources.slice(0,8).map(s=>`<div class="source">${esc(JSON.stringify(s))}</div>`).join('')}</details>`)}
</div>`; }
function renderFuture(){ const data=S.data.future_rice||[]; const q=S.filters.future||''; const cats=[...new Set(data.map(x=>x.category).filter(Boolean))].sort(); const filtered=data.filter(x=>!q||JSON.stringify(x).includes(q)); $('#future').innerHTML=`<div class="hero"><h1>お米の未来</h1><p>未来50件。読み物コーナーではなく、技術・気候・品種・流通などの未来テーマとして表示します。</p></div><div class="toolbar"><input placeholder="未来テーマ検索" value="${esc(q)}" oninput="S.filters.future=this.value;renderFuture()">${chips(cats)}</div><div class="list">${filtered.map(x=>`<div class="item"><h3>${esc(x.title_ja||x.title)}</h3><p>${chips([x.category,x.evidence_level,x.source_type])}</p><p><b>${esc(x.subtitle_ja||'')}</b></p><p>${esc(x.body_ja||x.summary_ja||x.text_ja||'')}</p><details><summary>出典</summary><div class="source">${esc(x.source_name||'')}<br>${esc(x.source_url||'')}</div></details></div>`).join('')}</div>`; }
function renderRankings(){ const r=S.data.rankings; const defs=(r&&r.rankings)||[]; const rows=S.data.ranking_items_template||[]; $('#rankings').innerHTML=`<div class="hero"><h1>世界の米ランキング</h1><p>4言語対応の通常コンテンツ。選択中の言語だけを表示します。順位明細はテンプレート行を保持しています。</p></div><div class="list">${defs.map(def=>{const items=rows.filter(x=>x.ranking_id===def.ranking_id && x.country_or_item_ja); return `<div class="item"><h3>${esc(t(def,'title')||def.ranking_id)}</h3><p>${esc(t(def,'value')||t(def,'description')||def.definition_ja||'')}</p><p>${chips([def.source_id,def.unit,def.update_frequency])}</p>${items.length?`<table>${items.slice(0,10).map(x=>`<tr><td>${esc(x.rank)}</td><td>${esc(t(x,'country_or_item'))}</td><td>${esc(x.value)} ${esc(x.unit)}</td></tr>`).join('')}</table>`:`<p class="warn">TOP10順位明細は未入力です。ranking_items_template には ${rows.filter(x=>x.ranking_id===def.ranking_id).length} 行の入力枠があります。</p>`}<details><summary>出典</summary><div class="source">${esc(def.source_id||'')} / ${esc(def.source_name||'')}<br>${esc(def.source_url||'')}</div></details></div>`}).join('')}</div>`; }
load().catch(e=>{document.body.innerHTML='<main><div class="card empty"><h1>データ読み込みエラー</h1><p>data/rice_navi_data_v32.json が同じ場所にアップロードされているか確認してください。</p><pre>'+esc(e.stack||e)+'</pre></div></main>'});
