
const DATA_URL = './data/rice_navi_data_v12.json';
let DATA = null;
let state = { view:'home', open:{fortune:true,history:false,story:false}, region: localStorage.getItem('riceNaviRegion') || '台湾', litCat:'すべて', lessonLevel:'初級', lessonIndex:0, futureId:null, storyId:null, varietyQuery:'', litQuery:'' };
const $ = (sel,root=document)=>root.querySelector(sel);
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function todayIndex(len, salt=0){const d=new Date(); const key=Math.floor((d - new Date(d.getFullYear(),0,0))/86400000)+salt; return len? key%len:0;}
async function init(){ DATA = await fetch(DATA_URL).then(r=>r.json()); render(); if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});} }
function setView(view){state.view=view; window.scrollTo({top:0,behavior:'smooth'}); render();}
function toggle(key){state.open[key]=!state.open[key]; renderHome();}
function appTop(title='RICE NAVI', back=false){return `<header class="topbar"><img class="logo" src="assets/rice_navi_rn_logo.png" alt="RICE NAVI"><div class="brand">${esc(title)}</div><div class="top-actions"><button class="icon-btn" onclick="setView('search')" aria-label="検索">🔍</button></div></header>`;}
function bottomNav(){const items=[['home','🏠','ホーム'],['meister','📘','学ぶ'],['literature','📚','文献'],['checks','✅','チェック'],['status','ℹ️','状況']];return `<nav class="bottomnav" aria-label="下部ナビ">${items.map(([v,ic,la])=>`<button class="${state.view===v?'active':''}" onclick="setView('${v}')"><span class="navicon">${ic}</span>${la}</button>`).join('')}</nav>`;}
function frame(content,title='RICE NAVI'){document.getElementById('app').innerHTML=appTop(title)+`<main class="main">${content}</main>`+bottomNav();}
function backBar(title){return `<div class="backbar"><button onclick="setView('home')">← ホームへ</button><h1 class="page-title">${esc(title)}</h1></div>`;}
function currentFortune(){return DATA.fortunes[todayIndex(DATA.fortunes.length)];}
function currentStory(){return DATA.stories[todayIndex(DATA.stories.length,10)];}
function currentHistory(){return DATA.histories.find(h=>h.region===state.region) || DATA.histories[0];}
function render(){ if(!DATA){document.getElementById('app').innerHTML='<p>読み込み中...</p>';return;} const routes={home:renderHome,meister:renderMeister,literature:renderLiterature,checks:renderChecks,status:renderStatus,stories:renderStories,future:renderFuture,varieties:renderVarieties,search:renderSearch,water:renderWater,environment:renderEnvironment,granary:renderGranary,glossary:renderGlossary}; (routes[state.view]||renderHome)(); }
function renderHome(){const f=currentFortune(), h=currentHistory(), st=currentStory(); const html=`
<section class="hero" aria-labelledby="fortune-title"><div class="fortune-grid"><div class="rice-illust" aria-hidden="true">🍚</div><div><h1 id="fortune-title">今日の米占い</h1><p><strong>${esc(f.title)}</strong></p><p>${esc(f.message)}</p><div class="mini-tags"><span class="mini-tag">ラッキー米：${esc(f.rice)}</span><span class="mini-tag">ラッキー工程：${esc(f.process)}</span></div><div class="button-row"><button class="secondary-btn" onclick="toggle('fortune')">${state.open.fortune?'閉じる':'詳しく見る'}</button></div></div></div>${state.open.fortune?`<div class="accordion-body"><p><strong>今日の一言：</strong>${esc(f.word)}</p><p class="small muted">占いはお楽しみ機能です。現場判断や診断には使わないでください。</p></div>`:''}</section>
${homeCard('history','📍','現在地のお米ヒストリー','今いる場所のお米の歴史を表示する',`現在地：${state.region}`,true)}
${state.open.history?`<div class="card"><h2>${esc(h.title)}</h2><p><strong>地域：${esc(h.region)}</strong></p><p>${esc(h.body)}</p><p class="notice small">${esc(h.note)}</p><div class="button-row"><select id="regionSel" aria-label="地域を変更">${DATA.histories.map(x=>`<option ${x.region===state.region?'selected':''}>${esc(x.region)}</option>`).join('')}</select><button class="secondary-btn" onclick="changeRegion()">地域を変更</button><button class="secondary-btn" onclick="toggle('history')">閉じる</button></div></div>`:''}
${homeCard('story','🌏','世界のライス物語','今週のストーリーを読む',st.title,true)}
${state.open.story?`<div class="card"><h2>今週のライス物語</h2><h3>${esc(st.title)}</h3><p>${esc(st.body)}</p><div class="button-row"><button class="primary-btn" onclick="setView('stories')">過去のストーリーを見る</button><button class="secondary-btn" onclick="toggle('story')">閉じる</button></div></div>`:''}
${homeCard('literature','📚','炊飯文献ライブラリ','炊飯に関する文献・claimを整理する','RICE NAVIの信頼性の中心',false,'highlight')}
${homeCard('meister','🎓','お米マイスター100','米の基本を100テーマで学ぶ','初級30・中級40・上級30',false)}
${homeCard('varieties','🔎','米品種図鑑','世界と日本の米品種を調べる',`${DATA.varieties.length}件を表示`,false)}
${homeCard('water','💧','水の相性チェック','pH、硬度、TDSなどから水と炊飯の関係を見る','入力して参考判定',false)}
${homeCard('environment','🌡️','気温・湿度・保管環境チェック','米の保管・吸水・カビリスクを見る','入力して参考判定',false)}
${homeCard('granary','🏚️','納米庫チェッカー','湿度、結露、残留米、カビ臭を確認する','即時停止条件あり',false)}
${homeCard('future','🌱','お米の未来','これからの米づくり、技術、食文化を読む','タイトル一覧から選ぶ',false)}
`;frame(html,'RICE NAVI');}
function homeCard(view,icon,title,sub,extra,accordion=false,cls=''){let on=accordion?`toggle('${view==='history'?'history':'story'}')`:`setView('${view}')`;return `<section class="card ${cls}"><button class="tap-card" onclick="${on}" aria-expanded="${accordion?state.open[view==='history'?'history':'story']:false}"><div class="card-row"><div class="card-icon">${icon}</div><div><h2 class="card-title">${esc(title)}</h2><p class="card-sub">${esc(sub)}</p>${extra?`<p class="small muted">${esc(extra)}</p>`:''}</div><div class="chev">${accordion?(state.open[view==='history'?'history':'story']?'⌃':'⌄'):'›'}</div></div></button></section>`;}
function changeRegion(){const sel=$('#regionSel'); if(sel){state.region=sel.value;localStorage.setItem('riceNaviRegion',state.region);renderHome();}}
function renderMeister(){let levels=['初級','中級','上級'];let lessons=DATA.meister_lessons.filter(x=>x.level===state.lessonLevel);let l=lessons[state.lessonIndex]||lessons[0];let html=`${backBar('お米マイスター100')}<p class="section-caption">文献ページに急に飛ばず、1テーマずつ順番に学びます。</p><div class="tabs">${levels.map(lv=>`<button class="tab ${lv===state.lessonLevel?'active':''}" onclick="state.lessonLevel='${lv}';state.lessonIndex=0;renderMeister()">${lv}</button>`).join('')}</div><div class="card"><span class="badge">${esc(l.level)}</span><span class="badge">${l.no}/100</span><h2>${String(l.no).padStart(2,'0')}　${esc(l.title)}</h2><p>${esc(l.body)}</p><div class="notice ok"><strong>今日のポイント</strong><br>${esc(l.point)}</div><p class="small muted">${esc(l.root)}</p><div class="lesson-nav"><button class="secondary-btn" onclick="prevLesson()">← 前へ</button><button class="primary-btn" onclick="nextLesson()">次へ →</button></div><div class="button-row"><button class="secondary-btn" onclick="setView('literature')">詳しい根拠を見る</button><button class="secondary-btn" onclick="renderTempTable()">温度と時間の表を見る</button></div></div>`;frame(html,'お米マイスター100');}
function prevLesson(){state.lessonIndex=Math.max(0,state.lessonIndex-1);renderMeister();}
function nextLesson(){let lessons=DATA.meister_lessons.filter(x=>x.level===state.lessonLevel);state.lessonIndex=Math.min(lessons.length-1,state.lessonIndex+1);renderMeister();}
function renderTempTable(){let rows=DATA.temperature_events.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td></tr>`).join('');let html=`${backBar('温度と時間の関係表')}<p>炊飯工程を、温度・時間・水分変化で見るための入口です。</p><table class="temp-table"><thead><tr><th>温度帯</th><th>米の変化</th><th>見るポイント</th></tr></thead><tbody>${rows}</tbody></table>`;frame(html,'温度と時間');}
function litCategories(){return ['すべて',...Array.from(new Set(DATA.literature_cards.map(c=>c.category))).sort()];}
function renderLiterature(){let cats=litCategories();let list=DATA.literature_cards.filter(c=>(state.litCat==='すべて'||c.category===state.litCat)&&(!state.litQuery||(`${c.title} ${c.short} ${c.terms}`).includes(state.litQuery)));let html=`${backBar('炊飯文献ライブラリ')}<p class="section-caption">カテゴリーを選び、最初はタイトルだけを読みます。詳細を開いたときだけclaim・条件・出典を表示します。</p><input class="searchbox" placeholder="文献カードを検索" value="${esc(state.litQuery)}" oninput="state.litQuery=this.value;renderLiterature()"><div class="category-bar">${cats.map(c=>`<button class="cat-btn ${c===state.litCat?'active':''}" onclick="state.litCat='${esc(c)}';renderLiterature()">${esc(c)}</button>`).join('')}</div><p class="small muted">表示：${list.length}件</p>${list.map((c,i)=>`<button class="list-button" onclick="openLit('${c.id}')"><span class="no">${i+1}.</span>${esc(c.title)}<br><span class="small muted">${esc(c.category)} / ${esc(c.status)}</span></button>`).join('')}<div id="litDetail"></div>`;frame(html,'文献ライブラリ');}
function openLit(id){let c=DATA.literature_cards.find(x=>x.id===id);let html=`<div class="detail"><button class="secondary-btn" onclick="$('#litDetail').innerHTML=''">閉じる</button><h3>${esc(c.title)}</h3><p>${esc(c.easy||c.short)}</p><dl class="kv"><dt>カテゴリー</dt><dd>${esc(c.category)}</dd><dt>文献から言えること</dt><dd>${esc(c.short)}</dd><dt>数値・条件</dt><dd>${esc(c.numbers||'文献条件を確認してください。')}</dd><dt>現場で見るポイント</dt><dd>${esc(c.field||'水温・時間・米の状態を確認してください。')}</dd><dt>注意</dt><dd>${esc(c.warning||'文献条件と現場条件を混同しないでください。')}</dd><dt>claim</dt><dd>${tagList(c.claim_ids)}</dd><dt>出典</dt><dd>${tagList(c.source_ids)}</dd></dl></div>`;$('#litDetail').innerHTML=html;$('#litDetail').scrollIntoView({behavior:'smooth',block:'start'});}
function tagList(s){return String(s||'').split(';').filter(Boolean).map(x=>`<span class="badge">${esc(x)}</span>`).join('')||'<span class="badge prep">未設定</span>';}
function renderStories(){let html=`${backBar('世界のライス物語')}<p class="section-caption">週1ストーリー形式。過去のストーリーも一覧で読めます。</p>${DATA.stories.map(s=>`<button class="list-button" onclick="openStory('${s.id}')"><span class="no">${s.week}週</span>${esc(s.title)}<br><span class="small muted">${esc(s.summary)}</span></button>`).join('')}<div id="storyDetail"></div>`;frame(html,'世界のライス物語');}
function openStory(id){let s=DATA.stories.find(x=>x.id===id);$('#storyDetail').innerHTML=`<div class="detail"><button class="secondary-btn" onclick="$('#storyDetail').innerHTML=''">閉じる</button><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p><p class="small muted">関連：${esc(s.related)}</p></div>`;$('#storyDetail').scrollIntoView({behavior:'smooth'});}
function renderFuture(){let html=`${backBar('お米の未来')}<p class="section-caption">タイトル一覧から読みたいものを選びます。空想ではなく、研究・政策・社会課題に沿った読み物です。</p>${DATA.future.map(item=>`<button class="list-button" onclick="openFuture('${item.future_id}')"><span class="badge">${esc(item.category)}</span>${esc(item.title_ja)}<br><span class="small muted">${esc(item.subtitle_ja||'')}</span></button>`).join('')}<div id="futureDetail"></div>`;frame(html,'お米の未来');}
function openFuture(id){let x=DATA.future.find(i=>i.future_id===id);$('#futureDetail').innerHTML=`<div class="detail"><button class="secondary-btn" onclick="$('#futureDetail').innerHTML=''">閉じる</button><h3>${esc(x.title_ja)}</h3><p><strong>${esc(x.subtitle_ja||'')}</strong></p><p>${esc(x.body_ja)}</p><p class="small muted">出典メモ：${esc(x.source_note||'研究・公的資料を確認')}</p></div>`;$('#futureDetail').scrollIntoView({behavior:'smooth'});}
function renderVarieties(){let q=state.varietyQuery;let list=DATA.varieties.filter(v=>!q || `${v.name} ${v.region} ${v.lineage} ${v.use}`.includes(q));let html=`${backBar('米品種図鑑')}<p class="section-caption">空画面にはせず、確認済みでない数値は「未確認」と表示します。一般参考値は入れません。</p><input class="searchbox" placeholder="品種名・地域・用途で検索" value="${esc(q)}" oninput="state.varietyQuery=this.value;renderVarieties()">${list.map(v=>`<button class="list-button" onclick="openVariety('${v.id}')"><strong>${esc(v.name)}</strong><br><span class="small muted">${esc(v.region)} / ${esc(v.lineage)} / ${esc(v.use)}</span></button>`).join('')}<div id="varietyDetail"></div>`;frame(html,'米品種図鑑');}
function openVariety(id){let v=DATA.varieties.find(x=>x.id===id);$('#varietyDetail').innerHTML=`<div class="detail"><button class="secondary-btn" onclick="$('#varietyDetail').innerHTML=''">閉じる</button><h3>${esc(v.name)}</h3><dl class="kv"><dt>国・地域</dt><dd>${esc(v.region)}</dd><dt>系統</dt><dd>${esc(v.lineage)}</dd><dt>粒形</dt><dd>${esc(v.grain_shape)}</dd><dt>アミロース</dt><dd>${esc(v.amylose)}</dd><dt>たんぱく質</dt><dd>${esc(v.protein)}</dd><dt>食味・食感</dt><dd>${esc(v.texture)}</dd><dt>主な用途</dt><dd>${esc(v.use)}</dd><dt>注意</dt><dd>${esc(v.note)}</dd></dl></div>`;$('#varietyDetail').scrollIntoView({behavior:'smooth'});}
function renderChecks(){let html=`${backBar('チェック')}<p class="section-caption">入力値から参考判定を表示します。実測値ではない場合は断定しません。</p>${checkCard('water','💧','水の相性チェック','pH、硬度、TDSなどを見る')}${checkCard('environment','🌡️','気温・湿度・保管環境チェック','温度・湿度から保管注意を見る')}${checkCard('granary','🏚️','納米庫チェッカー','結露・残留米・カビ臭などを確認')}`;frame(html,'チェック');}
function checkCard(view,icon,title,sub){return `<section class="card"><button class="tap-card" onclick="setView('${view}')"><div class="card-row"><div class="card-icon">${icon}</div><div><h2 class="card-title">${title}</h2><p class="card-sub">${sub}</p></div><div class="chev">›</div></div></button></section>`;}
function renderWater(){let html=`${backBar('水の相性チェック')}<p>${DATA.water_notes.intro}</p><p class="notice small">${DATA.water_notes.caution}</p><div class="card form-grid"><div class="field"><label>pH</label><input id="ph" type="number" step="0.1" value="7.2"></div><div class="field"><label>硬度 mg/L</label><input id="hardness" type="number" value="80"></div><div class="field"><label>TDS mg/L</label><input id="tds" type="number" value="180"></div><div class="field"><label>残留塩素 mg/L</label><input id="chlorine" type="number" step="0.1" value="0.3"></div><button class="primary-btn" onclick="judgeWater()">判定する</button></div><div id="waterResult"></div>`;frame(html,'水の相性');}
function judgeWater(){let ph=+$('#ph').value, hard=+$('#hardness').value, tds=+$('#tds').value, cl=+$('#chlorine').value;let msg=[],level='ok'; if(ph<6.5||ph>8.5){msg.push('pHが一般的な中性域から外れています。炊飯や設備条件への影響を確認してください。'); level='notice';} if(hard>120){msg.push('硬度が高めです。炊飯への影響だけでなく、配管・ノズルの付着リスクも確認してください。'); level='notice';} if(tds>300){msg.push('TDSが高めです。地域参考値か実測値かを確認してください。'); level='notice';} if(cl>1){msg.push('残留塩素が高めです。におい・処理水条件を確認してください。'); level='notice';} if(!msg.length) msg.push('入力値だけを見ると大きな注意はありません。ただし水質は配管・貯水槽・処理水で変わります。'); $('#waterResult').innerHTML=`<div class="card ${level==='ok'?'ok':'notice'}"><strong>参考判定</strong><p>${msg.map(esc).join('<br>')}</p><p class="small">次に見る項目：浸漬水温、加水量、配管・ノズルの状態</p></div>`;}
function renderEnvironment(){let html=`${backBar('気温・湿度・保管環境チェック')}<p>天気アプリではなく、米の保管と炊飯前条件を見るための機能です。</p><div class="card form-grid"><div class="field"><label>外気温 ℃</label><input id="ot" type="number" value="30"></div><div class="field"><label>室内温度 ℃</label><input id="it" type="number" value="28"></div><div class="field"><label>湿度 %</label><input id="rh" type="number" value="78"></div><div class="field"><label>米温 ℃</label><input id="rt" type="number" value="27"></div><button class="primary-btn" onclick="judgeEnv()">判定する</button></div><div id="envResult"></div>`;frame(html,'環境チェック');}
function judgeEnv(){let ot=+$('#ot').value,it=+$('#it').value,rh=+$('#rh').value,rt=+$('#rt').value;let msg=[],danger=false;if(rh>=70){msg.push('湿度が高めです。結露・カビ・虫害リスクを確認してください。');}if(it>=30||ot>=30){msg.push('高温域です。米の保管場所、直射日光、残留米の有無を確認してください。');}if(Math.abs(ot-it)>=10||Math.abs(it-rt)>=8){msg.push('温度差があります。結露の有無を確認してください。');}if(!msg.length)msg.push('大きな注意はありません。記録を残すと変化に気づきやすくなります。');$('#envResult').innerHTML=`<div class="card notice"><strong>参考判定</strong><p>${msg.map(esc).join('<br>')}</p><p class="small">次に見る項目：納米庫チェッカー、米水分、清掃日</p></div>`;}
function renderGranary(){let html=`${backBar('納米庫チェッカー')}<p>納米庫の湿度・結露・残留米・カビ臭などを確認します。</p><div class="card form-grid"><div class="field"><label>庫内温度 ℃</label><input id="gt" type="number" value="26"></div><div class="field"><label>庫内湿度 %</label><input id="gh" type="number" value="65"></div><div class="field"><label>前回清掃からの日数</label><input id="cleanDays" type="number" value="3"></div></div><div class="card"><label class="checkline"><input type="checkbox" id="condensation">結露・水濡れがある</label><label class="checkline"><input type="checkbox" id="residue">残留米・米くずがある</label><label class="checkline"><input type="checkbox" id="odor">カビ臭がある</label><label class="checkline"><input type="checkbox" id="visibleMold">目視カビがある</label><label class="checkline"><input type="checkbox" id="insects">虫の大量発生がある</label><button class="primary-btn" onclick="judgeGranary()">判定する</button></div><div id="granaryResult"></div>`;frame(html,'納米庫チェッカー');}
function judgeGranary(){let stop=$('#odor').checked||$('#visibleMold').checked||$('#insects').checked;let msg=[];if(stop){msg.push('使用停止・隔離・品質管理確認を行ってください。炊飯条件の調整対象ではありません。')}else{if($('#condensation').checked)msg.push('結露があります。原因確認、清掃、乾燥を行ってください。'); if($('#residue').checked)msg.push('残留米があります。次ロットに混ぜず、排出口・角部を清掃してください。'); if(+$('#gh').value>=70)msg.push('湿度が70%以上です。結露・カビに注意してください。'); if(+$('#cleanDays').value>7)msg.push('清掃間隔が長くなっています。清掃記録を確認してください。'); if(!msg.length)msg.push('大きな異常はありません。温度・湿度・清掃記録を継続してください。');}
$('#granaryResult').innerHTML=`<div class="card ${stop?'danger':'notice'}"><strong>${stop?'即時停止条件':'参考判定'}</strong><p>${msg.map(esc).join('<br>')}</p></div>`;}
function renderGlossary(){let entries=[];let g=DATA.glossary;if(Array.isArray(g)){entries=g.map(x=>({term:x.ja||x.term_ja||x.term||'',desc:x.en||x.zh_tw||''}));}else if(g.terms){entries=g.terms.map(x=>({term:x.ja||x.term_ja||x.term||'',desc:x.en||''}));}else{entries=[{term:'吸水',desc:'米が水を取り込むこと'},{term:'糊化',desc:'でんぷんが加熱と水で変化すること'}];}let html=`${backBar('用語集')}<p class="section-caption">専門語を短く確認します。</p>${entries.slice(0,80).map(e=>`<div class="card"><h2 class="card-title">${esc(e.term)}</h2><p class="small muted">${esc(e.desc)}</p></div>`).join('')}`;frame(html,'用語集');}
function renderSearch(){let html=`${backBar('検索')}<input class="searchbox" id="q" placeholder="米、吸水、温度、品種など" oninput="doSearch()"><div id="searchResult"></div>`;frame(html,'検索');}
function doSearch(){let q=$('#q').value.trim(); if(!q){$('#searchResult').innerHTML='';return;}let results=[];DATA.meister_lessons.filter(x=>`${x.title} ${x.body}`.includes(q)).slice(0,8).forEach(x=>results.push(['お米マイスター100',x.title,()=>{state.lessonLevel=x.level;state.lessonIndex=DATA.meister_lessons.filter(y=>y.level===x.level).findIndex(y=>y.id===x.id);setView('meister')} ]));DATA.literature_cards.filter(x=>`${x.title} ${x.short} ${x.terms}`.includes(q)).slice(0,8).forEach(x=>results.push(['炊飯文献ライブラリ',x.title,()=>{state.litQuery=q;setView('literature')} ]));DATA.varieties.filter(x=>`${x.name} ${x.region}`.includes(q)).slice(0,5).forEach(x=>results.push(['米品種図鑑',x.name,()=>{state.varietyQuery=q;setView('varieties')} ]));$('#searchResult').innerHTML=results.length?results.map((r,i)=>`<button class="list-button" id="sr${i}"><span class="badge">${esc(r[0])}</span>${esc(r[1])}</button>`).join(''):'<div class="card">該当する項目が見つかりませんでした。</div>';results.forEach((r,i)=>{$('#sr'+i).onclick=r[2]});}
function renderStatus(){let html=`${backBar('統合状況')}<div class="card"><h2>v12 ユニバーサルデザイン版</h2><p>空画面・戻れない画面・横幅バグを避け、まず日本語版で使える体験を優先しています。</p><dl class="kv"><dt>米占い</dt><dd>${DATA.fortunes.length}件</dd><dt>お米ヒストリー</dt><dd>${DATA.histories.length}地域</dd><dt>ライス物語</dt><dd>${DATA.stories.length}週分</dd><dt>お米の未来</dt><dd>${DATA.future.length}件</dd><dt>文献カード</dt><dd>${DATA.literature_cards.length}件</dd><dt>マイスター</dt><dd>${DATA.meister_lessons.length}件</dd><dt>米品種図鑑</dt><dd>${DATA.varieties.length}件</dd></dl></div><div class="card"><h2>ユニバーサルデザイン方針</h2><p>大きめ文字、大きめボタン、明確な戻る導線、横スクロールなし、準備中の空表示なしを基本にしています。</p></div>`;frame(html,'統合状況');}
init();
