'use strict';
const APP_VERSION = '29';
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
const app = $('#app');
const state = {manifest:null, home:null, learning:null, reading:null, check:null, modules:{}, view:'home', lang:'ja'};
const modulePath = {rice_varieties:'data/modules/rice_varieties.json', world_rankings:'data/modules/world_rice_rankings.json', jp_reading:'data/modules/jp_reading_corner.json'};
function esc(v){return String(v ?? '').replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function todayIndex(len){const d=new Date(); const seed=Number(`${d.getFullYear()}${d.getMonth()+1}${d.getDate()}`); return len ? seed % len : 0;}
async function fetchJson(path){const res = await fetch(`${path}?v=${APP_VERSION}`, {cache:'no-store'}); if(!res.ok) throw new Error(`${path} が読めません (${res.status})`); return await res.json();}
async function cleanupOldCaches(){try{if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations(); await Promise.all(regs.map(r=>r.unregister()));} if(window.caches){const keys=await caches.keys(); await Promise.all(keys.map(k=>caches.delete(k)));}}catch(e){console.warn('cache cleanup skipped', e);}}
async function boot(){try{await cleanupOldCaches(); state.manifest=await fetchJson('data/manifest.json'); state.home=await fetchJson('data/core/home.json'); state.learning=await fetchJson('data/core/learning.json'); state.reading=await fetchJson('data/core/reading.json'); state.check=await fetchJson('data/core/check.json'); renderApp();}catch(e){app.innerHTML=`<div class="error"><h1>RICE NAVIを起動できません</h1><p class="danger">${esc(e.message)}</p><p>GitHub上で <code>data/manifest.json</code>、<code>data/core/home.json</code>、<code>data/core/learning.json</code> があるか確認してください。</p><p>version: v${APP_VERSION}</p></div>`;}}
function renderApp(){app.innerHTML=`<div class="app"><header class="topbar"><div class="topbar-inner"><img class="logo" src="assets/RICE_NAVI_RN_icon.png?v=29" alt="RN"><div><div class="brand">RICE NAVI</div><div class="sub">米を知る・炊飯を考える・世界を見る</div></div><span class="pill">v${APP_VERSION}</span></div></header><main class="shell" id="main"></main><nav class="bottom-nav" id="bottomNav"></nav></div>`; renderBottom(); go('home');}
function renderBottom(){const nav=[['home','ホーム'],['learn','学ぶ'],['library','文献'],['catalog','図鑑'],['check','チェック'],['reading','読み物']]; $('#bottomNav').innerHTML=nav.map(n=>`<button data-go="${n[0]}" class="${state.view===n[0]?'active':''}">${n[1]}</button>`).join(''); $$('#bottomNav button').forEach(b=>b.onclick=()=>go(b.dataset.go));}
function go(view){const special=['rankings','jp_reading','varieties','dictionary','history']; if(special.includes(view)){openDetail(view); return;} if(view==='future'){view='reading';} state.view=view; renderBottom(); const main=$('#main'); if(!main)return; main.scrollIntoView({block:'start'}); if(view==='home') return renderHome(main); if(view==='learn') return renderLearn(main); if(view==='library') return renderLibrary(main); if(view==='catalog') return renderCatalog(main); if(view==='check') return renderCheck(main); if(view==='reading') return renderReading(main);}
function renderHero(){return `<section class="hero"><div class="grain-art"><span></span><span></span><span></span></div><h1>RICE NAVI</h1><p>今日の入口から、米辞典・文献・品種・水・保管・世界の米文化までつなげて見られる炊飯ナビです。</p></section>`;}
function todayTerm(){const arr=state.learning.terms||[]; return arr[todayIndex(arr.length)]||{};}
function todayFortune(){const arr=state.home.fortunes||[]; return arr[todayIndex(arr.length)]||{};}
function currentStory(){const arr=state.reading.stories||[]; return arr[todayIndex(arr.length)]||{};}
function renderHome(main){const term=todayTerm(), fortune=todayFortune(), story=currentStory(); main.innerHTML=renderHero()+`<section class="section"><div class="section-head"><h2>今日の入口</h2><span class="hint">軽く読んで、必要なら詳しく見る</span></div><div class="today-grid"><article class="card fortune-card accent"><div class="rice-illustration"></div><h3>今日の米占い</h3><p class="big-word">${esc(fortune.title||'炊き上がり吉')}</p><p>${esc(fortune.message||fortune.body||'一粒ずつ整える日です。')}</p><button class="btn secondary" data-open="fortune">詳しく見る</button></article><article class="card weather-card accent"><h3>今日の米天気</h3><p class="big-word">保管注意</p><p>天気を、米の吸水・保管・結露・納米庫注意に変換して見ます。</p><div class="tag-row"><span class="tag">湿度</span><span class="tag">結露</span><span class="tag">納米庫</span></div><button class="btn secondary" data-go="check">チェックを見る</button></article><article class="card word-card accent"><h3>今日の米言葉</h3><p class="big-word">${esc(term.term_ja||'吸水')}</p><p>${esc(term.app_note_ja||term.note_ja||'米辞典から今日の用語を表示します。')}</p><div class="tag-row"><span class="tag">${esc(term.term_en||'English')}</span><span class="tag">${esc(term.term_zh_tw||'繁体字')}</span></div><button class="btn secondary" data-open="term:${esc(term.id||term.term_ja)}">米辞典で詳しく見る</button></article></div></section><section class="section"><div class="section-head"><h2>大きな入口</h2><span class="hint">詳細ページに情報を集約</span></div><div class="grid">${tile('learn','📘','お米マイスター100','初級・中級・上級で学ぶ')} ${tile('library','🔎','炊飯文献ライブラリ','根拠・claim・条件を見る')} ${tile('catalog','🌾','米品種図鑑250','用途・食感・成分・出典')} ${tile('check','💧','水・保管・納米庫','天気と環境を米へ変換')} ${tile('reading','🌏','世界のライス物語','今週と過去1か月')} ${tile('rankings','📊','世界の米ランキング','4ヶ国語の通常コンテンツ')} ${tile('future','🚀','お米の未来50','研究・市場・環境の未来')} ${tile('jp_reading','☕','日本語限定読み物','添付Excelの読み物コーナー')}</div></section><section class="section"><div class="section-head"><h2>今週のライス物語</h2><button class="btn ghost" data-go="reading">過去1か月を見る</button></div><article class="card"><h3>${esc(story.title)}</h3><p>${esc(story.summary||story.body)}</p><button class="btn secondary" data-open="story:${story.id}">詳しく見る</button></article></section>`; bindActions();}
function tile(goTo, icon, title, desc){return `<button class="tile" data-go="${goTo}"><div class="icon">${icon}</div><h3>${esc(title)}</h3><p>${esc(desc)}</p></button>`;}
function bindActions(){ $$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); $$('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open)); }
function shellWithSide(title, body, active=''){return `<section class="section"><div class="section-head"><h2>${esc(title)}</h2><button class="btn ghost" data-go="home">ホームへ</button></div><div class="layout"><aside class="side card"><nav class="nav">${sideBtn('learn','学ぶ',active)}${sideBtn('library','文献',active)}${sideBtn('catalog','図鑑',active)}${sideBtn('check','チェック',active)}${sideBtn('reading','読み物',active)}</nav></aside><div class="content">${body}</div></div></section>`;}
function sideBtn(view,label,active){return `<button data-go="${view}" class="${active===view?'active':''}">${label}</button>`;}
function renderLearn(main){const levels=['初級','中級','上級']; const term=todayTerm(); const body=`<div class="card"><h3>今日の米言葉：${esc(term.term_ja)}</h3><p>${esc(term.app_note_ja||term.note_ja)}</p><button class="btn secondary" data-open="term:${esc(term.id||term.term_ja)}">関連リンクを見る</button></div><div class="toolbar"><button class="btn secondary" data-open="dictionary">米辞典を開く</button></div>${levels.map(level=>`<section class="section"><h2>${level}</h2><div class="list">${state.learning.meister.filter(x=>x.level===level).slice(0,10).map(x=>row(x.title,x.body,`No.${x.no} ${x.level}`,`meister:${x.id}`)).join('')}</div></section>`).join('')}`; main.innerHTML=shellWithSide('学ぶ',body,'learn'); bindActions();}
function renderLibrary(main){const cards=state.learning.learning_cards||[]; const cats=[...new Set(cards.map(x=>(x.terms||'未分類').split(';')[0].trim()).filter(Boolean))].slice(0,10); const body=`<p class="hint">一覧は軽く、詳細でclaim・条件・注意・関連トラブルを表示します。</p><input class="search" id="libSearch" placeholder="文献カードを検索"><div class="tag-row">${cats.map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div><div class="list" id="libList"></div>`; main.innerHTML=shellWithSide('炊飯文献ライブラリ',body,'library'); const paint=()=>{const q=($('#libSearch').value||'').toLowerCase(); $('#libList').innerHTML=cards.filter(x=>(x.title+x.short+x.easy+x.terms).toLowerCase().includes(q)).slice(0,60).map(x=>row(x.title,x.short||x.easy,`根拠 ${x.evidence||''} / ${x.terms||''}`,`card:${x.id}`)).join(''); bindActions();}; $('#libSearch').oninput=paint; paint(); bindActions();}
function renderCatalog(main){const body=`<div class="grid">${tile('dictionary','🈳','米辞典','今日の米言葉の本体')} ${tile('varieties','🌾','米品種図鑑250','検索・用途・食感・出典')} ${tile('rankings','📊','世界の米ランキング','4ヶ国語対応')} ${tile('history','🗺️','現在地のお米ヒストリー','地域から見る米の歴史')}</div><div id="catalogPane" class="section"></div>`; main.innerHTML=shellWithSide('図鑑',body,'catalog'); bindActions();}
function renderCheck(main){const body=`<div class="grid">${checkTile('今日の米天気','天気を保管・吸水・結露注意に変換','weather')} ${checkTile('水の相性チェック','地域参考水質と炊飯アドバイス','water')} ${checkTile('気温・湿度・保管環境','カビ・虫・結露・吸水への影響','storage')} ${checkTile('納米庫チェッカー','結露・湿度・温度帯を学ぶ','mold')}</div><div class="section"><h2>地域参考水質</h2><div class="list">${(state.check.region_water||[]).map(x=>row(x.area_name_ja,`硬度 ${x.total_hardness_mgL_CaCO3??'未確認'} mg/L / pH ${x.pH??'未確認'}`,x.water_supplier||'地域参考値',`regionwater:${x.region_id}`)).join('')}</div></div>`; main.innerHTML=shellWithSide('チェック',body,'check'); bindActions();}
function checkTile(title,desc,key){return `<button class="tile" data-open="check:${key}"><div class="icon">${key==='water'?'💧':key==='mold'?'🏭':key==='weather'?'🌦️':'🌡️'}</div><h3>${esc(title)}</h3><p>${esc(desc)}</p></button>`;}
function renderReading(main){const stories=state.reading.stories||[]; const past=stories.slice(0,5); const future=state.reading.future||[]; const body=`<section class="section"><h2>世界のライス物語</h2><p class="hint">今週＋過去1か月。全件を一気に出しません。</p><div class="list">${past.map(x=>row(x.title,x.summary,`Week ${x.week}`,`story:${x.id}`)).join('')}</div></section><section class="section"><h2>お米の未来50</h2><div class="list">${future.slice(0,20).map(x=>row(x.title,x.subtitle||x.body,x.category,`future:${x.id}`)).join('')}</div></section><section class="section"><div class="grid">${tile('rankings','📊','世界の米ランキング','通常コンテンツ・4ヶ国語')} ${tile('jp_reading','☕','日本語限定読み物','添付Excelの読み物')}</div></section>`; main.innerHTML=shellWithSide('読み物',body,'reading'); bindActions();}
function row(title, desc, meta, open){return `<article class="row"><div class="row-title">${esc(title)}</div><div>${esc(desc||'')}</div><div class="row-meta">${esc(meta||'')}</div><div><button class="btn secondary" data-open="${open}">詳しく見る</button></div></article>`;}
async function openModule(name){if(!state.modules[name]) state.modules[name]=await fetchJson(modulePath[name]); return state.modules[name];}
async function openDetail(key){try{ if(key==='dictionary') return showDictionary(); if(key==='varieties'||key==='rankings'||key==='jp_reading') return openSpecial(key); if(key==='history') return showHistory(); if(key==='fortune') return modal('今日の米占い', `<p>${esc(todayFortune().message||todayFortune().body||'')}</p><p class="hint">今日の入口として軽く表示します。関連して今日の米言葉も確認できます。</p>`); const [type,id]=key.split(':'); if(type==='term') return showTerm(id); if(type==='card') return showCard(id); if(type==='meister') return showMeister(id); if(type==='story') return showStory(id); if(type==='future') return showFuture(id); if(type==='check') return showCheck(id); if(type==='regionwater') return showRegionWater(id); }catch(e){modal('読込エラー', `<p class="danger">${esc(e.message)}</p>`);} }
function modal(title, html){const back=document.createElement('div'); back.className='modal-back'; back.innerHTML=`<div class="modal"><button class="btn ghost close">閉じる</button><h2>${esc(title)}</h2>${html}</div>`; document.body.appendChild(back); $('.close',back).onclick=()=>back.remove(); back.onclick=e=>{if(e.target===back)back.remove();};}
function findBy(arr, id){return (arr||[]).find(x=>x.id===id || x.claim_id===id || String(x.no)===id) || {};}
function relatedCardsByTerm(term){const t=(term.term_ja||term.id||'').toLowerCase(); return (state.learning.learning_cards||[]).filter(c=>(c.title+c.short+c.easy+c.terms).toLowerCase().includes(t)).slice(0,5);}
function relatedTroubles(term){const t=(term.term_ja||'').toLowerCase(); return (state.learning.troubles||[]).filter(x=>Object.values(x).join(' ').toLowerCase().includes(t)).slice(0,5);}
function showTerm(id){const term=(state.learning.terms||[]).find(x=>x.id===id||x.term_ja===id)||todayTerm(); const cards=relatedCardsByTerm(term); const troubles=relatedTroubles(term); modal('今日の米言葉 / 米辞典', `<div class="rice-illustration"></div><p class="big-word">${esc(term.term_ja)}</p><div class="cols"><div class="mini"><b>English</b><br>${esc(term.term_en)}</div><div class="mini"><b>繁体字</b><br>${esc(term.term_zh_tw)}</div><div class="mini"><b>簡体字</b><br>${esc(term.term_zh_cn)}</div><div class="mini"><b>説明</b><br>${esc(term.app_note_ja||term.note_ja)}</div></div><h3>関連文献</h3>${cards.length?cards.map(c=>row(c.title,c.short,c.terms,`card:${c.id}`)).join(''):'<p class="hint">直接一致する文献はありません。米辞典から広げます。</p>'}<h3>関連トラブル</h3>${troubles.length?troubles.map(t=>`<div class="mini"><b>${esc(t.trouble_or_target)}</b><br>${esc(t.evidence_scope_or_step4)}</div>`).join(''):'<p class="hint">関連トラブルは未設定です。</p>'}`); bindActions();}
function showDictionary(){const terms=state.learning.terms||[]; modal('米辞典', `<p class="hint">今日の米言葉の本体データ。4ヶ国語と関連リンクに使います。</p><div class="list">${terms.map(t=>row(t.term_ja,t.app_note_ja||t.note_ja,`${t.term_en} / ${t.term_zh_tw}`,`term:${t.id||t.term_ja}`)).join('')}</div>`); bindActions();}
function showCard(id){const c=findBy(state.learning.learning_cards,id); const ids=String(c.claim_ids||'').split(';').map(s=>s.trim()).filter(Boolean); const claims=(state.learning.process_claims||[]).filter(x=>ids.includes(x.id)||ids.includes(x.claim_id)); modal('炊飯文献カード', `<h3>${esc(c.title)}</h3><p>${esc(c.easy||c.short)}</p><div class="cols"><div class="mini"><b>数値・条件</b><br>${esc(c.numbers||'未確認')}</div><div class="mini"><b>見るポイント</b><br>${esc(c.field||'')}</div><div class="mini"><b>注意</b><br>${esc(c.warning||'')}</div><div class="mini"><b>出典ID</b><br>${esc(c.source_ids||'')}</div></div><h3>関連claim</h3>${claims.length?claims.map(x=>`<div class="mini"><b>${esc(x.id||x.claim_id)}</b><br>${esc(x.claim||x.theme)}<br><span class="hint">${esc(x.condition||'')}</span></div>`).join(''):'<p class="hint">claim_idはありますが一致データは未確認です。</p>'}`);}
function showMeister(id){const m=findBy(state.learning.meister,id); modal('お米マイスター100', `<h3>${esc(m.no)}. ${esc(m.title)}</h3><p>${esc(m.body)}</p><div class="mini"><b>今日のポイント</b><br>${esc(m.point)}</div><p class="hint">必要な人だけ文献ライブラリへ進みます。</p>`);}
function showStory(id){const s=findBy(state.reading.stories,id); modal('世界のライス物語', `<h3>${esc(s.title)}</h3><p>${esc(s.body||s.summary)}</p><div class="tag-row"><span class="tag">文化</span><span class="tag">食感</span><span class="tag">品種</span><span class="tag">炊飯</span></div>`);}
function showFuture(id){const f=findBy(state.reading.future,id); modal('お米の未来', `<h3>${esc(f.title)}</h3><p class="hint">${esc(f.category)} / 根拠 ${esc(f.evidence_level)}</p><p>${esc(f.body)}</p><p class="source">${esc(f.source_url||'')}</p>`);}
function showCheck(id){if(id==='water'){modal('水の相性チェック', `<p>GPSや地域から水質の参考値を見て、炊飯の硬さ・粘り・香り・設備スケール注意につなげます。GPSが水を測定するわけではありません。</p><h3>硬度ルール</h3>${state.check.water_rules.filter(x=>x.parameter==='total_hardness').map(x=>`<div class="mini"><b>${esc(x.class_ja)}</b><br>${esc(x.advice_ja)}<br><span class="hint">${esc(x.min_value)}〜${esc(x.max_value||'以上')} ${esc(x.unit)}</span></div>`).join('')}`);} else if(id==='mold'){modal('納米庫チェッカー', `<p>納米庫はチェックだけでなく、結露・湿度・温度帯・残米・カビ臭を見る学習ページとして扱います。</p><h3>確認ポイント</h3>${state.check.mold_checklist.map(x=>`<div class="mini"><b>${esc(x.check_area)}</b><br>${esc(x.check_item)}<br><span class="hint">NG時: ${esc(x.action_if_ng)}</span></div>`).join('')}`);} else if(id==='weather'||id==='storage'){modal(id==='weather'?'今日の米天気':'気温・湿度・保管環境', `<p>気温・湿度・雨・温度差を、米袋・保管室・納米庫・吸水時間への注意に変換します。</p><div class="tag-row"><span class="tag warn">湿度70%+注意</span><span class="tag warn">温度差で結露</span><span class="tag">吸水速度</span></div>`);} }
function showRegionWater(id){const r=(state.check.region_water||[]).find(x=>x.region_id===id)||{}; modal('地域参考水質', `<h3>${esc(r.area_name_ja)}</h3><div class="cols"><div class="mini"><b>pH</b><br>${esc(r.pH??'未確認')}</div><div class="mini"><b>硬度</b><br>${esc(r.total_hardness_mgL_CaCO3??'未確認')} mg/L</div><div class="mini"><b>TDS</b><br>${esc(r.tds_mgL??'未確認')}</div><div class="mini"><b>残留塩素</b><br>${esc(r.residual_chlorine_mgL??'未確認')}</div></div><p class="source">${esc(r.source_url||'')}</p>`);}
async function openSpecial(key){ if(key==='varieties'){const d=await openModule('rice_varieties'); return showVarieties(d);} if(key==='rankings'){const d=await openModule('world_rankings'); return showRankings(d);} if(key==='jp_reading'){const d=await openModule('jp_reading'); return showJPReading(d);} }
function showVarieties(d){const arr=d.varieties||[]; modal('米品種図鑑250', `<p class="hint">250件マスターを正式データとして表示。未確認値は未確認のまま扱います。</p><input class="search" id="vSearch" placeholder="品種名・国・用途で検索"><div id="vList" class="list"></div>`); const paint=()=>{const q=($('#vSearch').value||'').toLowerCase(); $('#vList').innerHTML=arr.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q)).slice(0,80).map(x=>`<article class="row"><div class="row-title">${esc(x.display_name_ja||x.variety_name)}</div><div>${esc(x.country_ja||x.origin_country_ja||'')} / ${esc(x.rice_type||'未確認')} / ${esc(x.grain_shape||'未確認')}</div><div class="row-meta">用途: ${esc(x.use_category_primary||x.main_uses||'未確認')}｜アミロース: ${esc(x.amylose_value??x.amylose_range??'未確認')}｜たんぱく質: ${esc(x.protein_value??x.protein_range??'未確認')}</div><button class="btn secondary" data-var="${esc(x.id)}">詳細</button></article>`).join(''); $$('[data-var]').forEach(b=>b.onclick=()=>{const x=arr.find(v=>v.id===b.dataset.var)||{}; modal(x.display_name_ja||x.variety_name, `<div class="cols"><div class="mini"><b>国・地域</b><br>${esc(x.origin_country_ja||x.country_ja)}</div><div class="mini"><b>米タイプ</b><br>${esc(x.rice_type||'未確認')}</div><div class="mini"><b>粒形</b><br>${esc(x.grain_shape||'未確認')}</div><div class="mini"><b>用途</b><br>${esc(x.use_category_primary||x.main_uses||'未確認')}</div><div class="mini"><b>アミロース</b><br>${esc(x.amylose_value??x.amylose_range??'未確認')}</div><div class="mini"><b>たんぱく質</b><br>${esc(x.protein_value??x.protein_range??'未確認')}</div></div><p>${esc(x.notes||x.safe_app_note_ja_v1_4||'')}</p><p class="source">${esc(x.source_urls||'')}</p>`);});}; $('#vSearch').oninput=paint; paint();}
function showRankings(d){const arr=d.rankings||[]; modal('世界の米ランキング', `<p class="hint">4ヶ国語対応の通常コンテンツです。通常コンテンツです。</p><div class="list">${arr.map(r=>`<article class="row"><div class="row-title">${esc(r.display_title?.ja||r.ranking_name?.ja)}</div><div>${esc(r.short_desc?.ja||'')}</div><div class="row-meta">${esc(r.source_name)} / ${esc(r.unit)} / ${esc(r.status)}</div><button class="btn secondary" data-ranking="${esc(r.ranking_id)}">詳しく見る</button></article>`).join('')}</div>`); $$('[data-ranking]').forEach(b=>b.onclick=()=>{const r=arr.find(x=>x.ranking_id===b.dataset.ranking)||{}; modal(r.display_title?.ja||'世界の米ランキング', `<div class="cols"><div class="mini"><b>日本語</b><br>${esc(r.ranking_name?.ja)}</div><div class="mini"><b>English</b><br>${esc(r.ranking_name?.en)}</div><div class="mini"><b>繁体字</b><br>${esc(r.ranking_name?.['zh-TW'])}</div><div class="mini"><b>簡体字</b><br>${esc(r.ranking_name?.['zh-CN'])}</div></div><p>${esc(r.short_desc?.ja)}</p><p class="hint">定義: ${esc(r.calculation_method)}</p><p class="source">Source: ${esc(r.source_name)}</p>`);});}
function showJPReading(d){const arr=d.items||[]; modal('日本語限定読み物', `<p class="hint">日本語限定なのは、この添付Excel由来の読み物コーナーです。</p><input class="search" id="jpSearch" placeholder="シリーズ・タイトルで検索"><div id="jpList" class="list"></div>`); const paint=()=>{const q=($('#jpSearch').value||'').toLowerCase(); $('#jpList').innerHTML=arr.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q)).slice(0,80).map(x=>`<article class="row"><div class="row-title">${esc(x.title_or_question)}</div><div>${esc(x.text_ja)}</div><div class="row-meta">${esc(x.series_name)} / ${esc(x.status)}</div></article>`).join('');}; $('#jpSearch').oninput=paint; paint();}
function showHistory(){const arr=state.home.histories||[]; modal('現在地のお米ヒストリー', `<p class="hint">現在地または選択地域から、土地のお米の歴史へ入ります。</p><div class="list">${arr.map(x=>row(x.title||x.region,x.summary||x.body,x.region||'',`historyitem:${x.id||x.region}`)).join('')}</div>`);}
window.addEventListener('error', e=>{console.error(e.error||e.message);});
boot();
